-- Start of DDL Script for View TEST.VW_SL_TK_SDDPNN
-- Generated 20/09/2013 11:36:09 AM from TEST@DCNC

CREATE OR REPLACE VIEW vw_sl_tk_sddpnn (
   err_id,
   err_name,
   field_name,
   kytt_tu_ngay,
   ky_kkhai_tu_ngay,
   ngay_htoan,
   ma_tkhai,
   ltd,
   ma_loai_tk,
   ngay_nop_tk,
   trang_thai_tk,
   ma_tmuc,
   nnt_tin,
   nnt_ten_nnt,
   nnt_ngcap_mst,
   nnt_cap,
   nnt_chuong,
   nnt_loai,
   nnt_khoan,
   nnt_ngay_sinh,
   nnt_dia_chi,
   nnt_ma_tinh,
   nnt_ten_tinh,
   nnt_ma_huyen,
   nnt_ten_huyen,
   nnt_ma_xa,
   nnt_ten_xa,
   nnt_ma_thon,
   nnt_ten_thon,
   nnt_cmnd,
   nnt_cmnd_ngay_cap,
   nnt_cmnd_noi_cap,
   thd_dia_chi,
   thd_ma_tinh,
   thd_ten_tinh,
   thd_ma_huyen,
   thd_ten_huyen,
   thd_ma_xa,
   thd_ten_xa,
   thd_ma_thon,
   thd_ten_thon,
   thd_gcn,
   thd_gcn_so,
   thd_gcn_ngay_cap,
   thd_thua_dat_so,
   thd_ban_do_so,
   thd_gcn_dien_tich,
   thd_dtich_sd_tte,
   thd_gcn_ma_md,
   thd_gcn_ten_md,
   thd_han_muc,
   thd_chua_gcn,
   thd_chua_gcn_dtich,
   thd_chua_gcn_ma_md,
   thd_chua_gcn_ten_md,
   mgi_ma_ly_do,
   mgi_ten_ly_do,
   mgi_ghi_chu,
   mgi_so_tien,
   mgi_ty_le,
   cct_dtich_sd_tte,
   cct_han_muc,
   cct_ma_loai_dat,
   cct_ten_loai_dat,
   cct_ma_duong,
   cct_ten_duong,
   cct_ma_doan_duong,
   cct_ten_doan_duong,
   cct_ma_loai_duong,
   cct_ten_loai_duong,
   cct_ma_vi_tri,
   cct_ten_vi_tri,
   cct_he_so,
   cct_ma_gia_dat,
   cct_gia_dat,
   cct_gia_1m2_dat,
   cct_co_bke,
   dato_dtich_trong_hm,
   dato_dtich_duoi3,
   dato_dtich_vuot3,
   dato_stpn,
   ccu_dtich,
   ccu_stpn,
   ccu_he_so,
   skd_dtich,
   skd_stpn,
   smd_dtich,
   smd_ma_md,
   smd_ten_md,
   smd_gia_1m2_dat,
   smd_stpn,
   lch_dtich,
   lch_ma_md,
   lch_ten_md,
   lch_gia_1m2_dat,
   lch_stpn,
   stpn_truoc_mgi,
   stpn_tong,
   stpn_clech_bsung,
   dkn_nop_5nam,
   dkn_so_tien,
   ttk_dato_stpn,
   ttk_ccu_stpn,
   ttk_skd_stpn,
   ttk_smd_stpn,
   ttk_lch_stpn,
   dlt_tin,
   dlt_ten_dlt,
   dlt_dia_chi,
   dlt_ma_tinh,
   dlt_ten_tinh,
   dlt_ma_huyen,
   dlt_ten_huyen,
   dlt_ma_xa,
   dlt_ten_xa,
   dlt_ma_thon,
   dlt_ten_thon,
   dlt_so_dt,
   dlt_so_hdong,
   dlt_ngay_hdong,
   sthue_pnop )
AS
SELECT   ERR_ID,
         ERR_NAME,
         FIELD_NAME,
         kytt_tu_ngay,
         ky_kkhai_tu_ngay,
         ngay_htoan,
         ma_tkhai,
         ltd,
         ma_loai_tk,
         ngay_nop_tk,
         trang_thai_tk,
         ma_tmuc,
         nnt_tin,
         nnt_ten_nnt,
         nnt_ngcap_mst,
         nnt_cap,
         nnt_chuong,
         nnt_loai,
         nnt_khoan,
         nnt_ngay_sinh,
         nnt_dia_chi,
         nnt_ma_tinh,
         nnt_ten_tinh,
         nnt_ma_huyen,
         nnt_ten_huyen,
         nnt_ma_xa,
         nnt_ten_xa,
         nnt_ma_thon,
         nnt_ten_thon,
         nnt_cmnd,
         nnt_cmnd_ngay_cap,
         nnt_cmnd_noi_cap,
         thd_dia_chi,
         thd_ma_tinh,
         thd_ten_tinh,
         thd_ma_huyen,
         thd_ten_huyen,
         thd_ma_xa,
         thd_ten_xa,
         thd_ma_thon,
         thd_ten_thon,
         thd_gcn,
         thd_gcn_so,
         thd_gcn_ngay_cap,
         thd_thua_dat_so,
         thd_ban_do_so,
         thd_gcn_dien_tich,
         thd_dtich_sd_tte,
         thd_gcn_ma_md,
         thd_gcn_ten_md,
         thd_han_muc,
         thd_chua_gcn,
         thd_chua_gcn_dtich,
         thd_chua_gcn_ma_md,
         thd_chua_gcn_ten_md,
         mgi_ma_ly_do,
         mgi_ten_ly_do,
         mgi_ghi_chu,
         mgi_so_tien,
         mgi_ty_le,
         cct_dtich_sd_tte,
         cct_han_muc,
         cct_ma_loai_dat,
         cct_ten_loai_dat,
         cct_ma_duong,
         cct_ten_duong,
         cct_ma_doan_duong,
         cct_ten_doan_duong,
         cct_ma_loai_duong,
         cct_ten_loai_duong,
         cct_ma_vi_tri,
         cct_ten_vi_tri,
         cct_he_so,
         cct_ma_gia_dat,
         cct_gia_dat,
         cct_gia_1m2_dat,
         cct_co_bke,
         dato_dtich_trong_hm,
         dato_dtich_duoi3,
         dato_dtich_vuot3,
         dato_stpn,
         ccu_dtich,
         ccu_stpn,
         ccu_he_so,
         skd_dtich,
         skd_stpn,
         smd_dtich,
         smd_ma_md,
         smd_ten_md,
         smd_gia_1m2_dat,
         smd_stpn,
         lch_dtich,
         lch_ma_md,
         lch_ten_md,
         lch_gia_1m2_dat,
         lch_stpn,
         stpn_truoc_mgi,
         stpn_tong,
         stpn_clech_bsung,
         dkn_nop_5nam,
         dkn_so_tien,
         ttk_dato_stpn,
         ttk_ccu_stpn,
         ttk_skd_stpn,
         ttk_smd_stpn,
         ttk_lch_stpn,
         dlt_tin,
         dlt_ten_dlt,
         dlt_dia_chi,
         dlt_ma_tinh,
         dlt_ten_tinh,
         dlt_ma_huyen,
         dlt_ten_huyen,
         dlt_ma_xa,
         dlt_ten_xa,
         dlt_ma_thon,
         dlt_ten_thon,
         dlt_so_dt,
         dlt_so_hdong,
         dlt_ngay_hdong,
         sthue_pnop
    FROM   (SELECT    a.err_id err_id,
                     (SELECT   c.err_name
                        FROM   tb_lst_err c
                       WHERE   a.err_id = c.err_id)
         err_name,
         a.field_name,
         b.kytt_tu_ngay,
         b.ky_kkhai_tu_ngay,
         b.ngay_htoan,
         b.ma_tkhai,
         b.ltd,
         b.ma_loai_tk,
         b.ngay_nop_tk,
         b.trang_thai_tk,
         b.ma_tmuc,
         b.nnt_tin,
         b.nnt_ten_nnt,
         b.nnt_ngcap_mst,
         b.nnt_cap,
         b.nnt_chuong,
         b.nnt_loai,
         b.nnt_khoan,
         b.nnt_ngay_sinh,
         b.nnt_dia_chi,
         b.nnt_ma_tinh,
         (SELECT   c.prov_name
            FROM   tb_pnn_dm_province c
           WHERE   c.province = b.nnt_ma_tinh)
             nnt_ten_tinh,
         b.nnt_ma_huyen,
         (SELECT   c.dist_name
            FROM   tb_pnn_dm_district c
           WHERE   c.dist_code = b.nnt_ma_huyen)
             nnt_ten_huyen,
         b.nnt_ma_xa,
         (SELECT   c.comm_name
            FROM   tb_pnn_dm_commune c
           WHERE   c.comm_code = b.nnt_ma_xa)
             nnt_ten_xa,
         b.nnt_ma_thon,
         (SELECT   c.ten
            FROM   tb_pnn_dm_thon c
           WHERE   c.ma_thon = b.nnt_ma_thon)
             nnt_ten_thon,
         b.nnt_cmnd,
         b.nnt_cmnd_ngay_cap,
         b.nnt_cmnd_noi_cap,
         b.nnt_so_dt,
         b.nnt_so_tk,
         b.nnt_ngan_hang,
         b.nnt_nnkt_ctiet,
         b.thd_dia_chi,
         b.thd_ma_tinh,
         (SELECT   c.prov_name
            FROM   tb_pnn_dm_province c
           WHERE   c.province = b.thd_ma_tinh)
             thd_ten_tinh,
         b.thd_ma_huyen,
         (SELECT   c.dist_name
            FROM   tb_pnn_dm_district c
           WHERE   c.dist_code = b.thd_ma_huyen)
             thd_ten_huyen,
         b.thd_ma_xa,
         (SELECT   c.comm_name
            FROM   tb_pnn_dm_commune c
           WHERE   c.comm_code = b.thd_ma_xa)
             thd_ten_xa,
         b.thd_ma_thon,
         (SELECT   c.ten
            FROM   tb_pnn_dm_thon c
           WHERE   c.ma_thon = b.thd_ma_thon)
             thd_ten_thon,
         b.thd_gcn,
         b.thd_gcn_so,
         b.thd_gcn_ngay_cap,
         b.thd_thua_dat_so,
         b.thd_ban_do_so,
         b.thd_gcn_dien_tich,
         b.thd_dtich_sd_tte,
         b.thd_gcn_ma_md,
         (select c.ten from tb_pnn_dm_muc_dich_sd c where c.ma_muc_dich = b.thd_gcn_ma_md) thd_gcn_ten_md,
         b.thd_han_muc,
         b.thd_chua_gcn,
         b.thd_chua_gcn_dtich,
         b.thd_chua_gcn_ma_md,
         (select c.ten from tb_pnn_dm_muc_dich_sd c where c.ma_muc_dich = b.thd_chua_gcn_ma_md) thd_chua_gcn_ten_md,
         b.mgi_ma_ly_do,
         (SELECT c.ten FROM tb_pnn_dm_mien_giam c where c.ma_lydo = b.mgi_ma_ly_do
         and c.ma_tinh = substr(b.ma_cqt,1,3)) mgi_ten_ly_do,
         b.mgi_ghi_chu,
         b.mgi_so_tien,
         b.mgi_ty_le,
         b.cct_dtich_sd_tte,
         b.cct_han_muc,
         b.cct_ma_loai_dat,
         (SELECT c.ten FROM tb_pnn_dm_loai_dat c where c.ma_loai_dat = b.cct_ma_loai_dat
         and c.ma_tinh = substr(b.ma_cqt,1,3) ) cct_ten_loai_dat,
         b.cct_ma_duong,
         (SELECT c.ten FROM tb_pnn_dm_ten_duong c where c.ma_duong = b.cct_ma_duong
         and c.ma_tinh = substr(b.ma_cqt,1,3) and rownum = 1) cct_ten_duong,
         b.cct_ma_doan_duong,
         (SELECT c.ten_doan_duong FROM tb_pnn_dm_doan_duong c where c.ma_doan_duong = b.cct_ma_doan_duong
         and c.ma_huyen = b.ma_cqt  and rownum = 1) cct_ten_doan_duong,
         b.cct_ma_loai_duong,
         (SELECT c.ten  FROM tb_pnn_dm_loai_duong c where c.ma_loai_duong = b.cct_ma_loai_duong
         and c.ma_tinh = substr(b.ma_cqt,1,3)  and rownum = 1) cct_ten_loai_duong,
         b.cct_ma_vi_tri,
         (SELECT c.ten FROM tb_pnn_dm_vi_tri c where c.ma_vi_tri = b.cct_ma_vi_tri
         and c.ma_tinh = substr(b.ma_cqt,1,3)  and rownum = 1) cct_ten_vi_tri,
         b.cct_he_so,
         b.cct_ma_gia_dat,
         b.cct_gia_dat,
         b.cct_gia_1m2_dat,
         b.cct_co_bke,
         b.dato_dtich_trong_hm,
         b.dato_dtich_duoi3,
         b.dato_dtich_vuot3,
         b.dato_stpn,
         b.ccu_dtich,
         b.ccu_stpn,
         b.ccu_he_so,
         b.skd_dtich,
         b.skd_stpn,
         b.smd_dtich,
         b.smd_ma_md,
         (select c.ten from tb_pnn_dm_muc_dich_sd c where c.ma_muc_dich = b.smd_ma_md) smd_ten_md,
         b.smd_gia_1m2_dat,
         b.smd_stpn,
         b.lch_dtich,
         b.lch_ma_md,
         (select c.ten from tb_pnn_dm_muc_dich_sd c where c.ma_muc_dich = b.lch_ma_md) lch_ten_md,
         b.lch_gia_1m2_dat,
         b.lch_stpn,
         b.stpn_truoc_mgi,
         b.stpn_tong,
         b.stpn_clech_bsung,
         b.dkn_nop_5nam,
         b.dkn_so_tien,
         b.ttk_dato_stpn,
         b.ttk_ccu_stpn,
         b.ttk_skd_stpn,
         b.ttk_smd_stpn,
         b.ttk_lch_stpn,
         b.dlt_tin,
         b.dlt_ten_dlt,
         b.dlt_dia_chi,
         b.dlt_ma_tinh,
         (SELECT   c.prov_name
            FROM   tb_pnn_dm_province c
           WHERE   c.province = b.dlt_ma_tinh)
             dlt_ten_tinh,
         b.dlt_ma_huyen,
         (SELECT   c.dist_name
            FROM   tb_pnn_dm_district c
           WHERE   c.dist_code = b.dlt_ma_huyen)
             dlt_ten_huyen,
         b.dlt_ma_xa,
         (SELECT   c.comm_name
            FROM   tb_pnn_dm_commune c
           WHERE   c.comm_code = b.dlt_ma_xa)
             dlt_ten_xa,
         b.dlt_ma_thon,
         (SELECT   c.ten
            FROM   tb_pnn_dm_thon c
           WHERE   c.ma_thon = b.dlt_ma_thon)
             dlt_ten_thon,
         b.dlt_so_dt,
         b.dlt_so_hdong,
         b.dlt_ngay_hdong,
         b.sthue_pnop
              FROM   tb_data_error a, tb_tk_sddpnn b
             WHERE       a.rid = b.ROWID
                     AND a.table_name in ('TB_TK_SDDPNN','TB_TK_SDDPNN_01_NNT')
                     AND a.short_name = b.short_name
                     AND b.short_name = USERENV ('client_info')
                     AND a.update_no = 0)
ORDER BY   err_id, ma_tkhai
/

-- End of DDL Script for View TEST.VW_SL_TK_SDDPNN

