INSERT INTO tb_tables 
VALUES(3,'EXT_TKTMB_DTL',NULL,'PK_EXT_TKTMB_DTL_ID','ID','IDX_EXT_TKTMB_DTL_ID','ID','QLT-APP');
INSERT INTO tb_tables 
VALUES(8,'EXT_PNN_NO',NULL,'PK_EXT_PNN_NO_ID','ID','IDX_EXT_PNN_NO_ID',NULL,'PNN-APP');
INSERT INTO tb_tables 
VALUES(4,'ext_errors',NULL,'ext_pk_errors','seq_number',NULL,NULL,NULL);
INSERT INTO tb_tables 
VALUES(5,'EXT_DMUC_TKHAI',NULL,'PK_EXT_DMUC_TKHAI_ID','ID','IDX_TMS_DMUC_TKHAI_ID','ID','QLT-APP');
INSERT INTO tb_tables 
VALUES(6,'EXT_CCTT_HDR',NULL,'PK_EXT_CCTT_HDR_ID','ID','IDX_EXT_CCTT_HDR_ID','ID','QLT-APP');
INSERT INTO tb_tables 
VALUES(7,'EXT_CCTT_DTL',NULL,'PK_EXT_CCTT_DTL_ID','ID','IDX_EXT_CCTT_DTL_ID','ID','QLT-APP');
INSERT INTO tb_tables 
VALUES(1,'EXT_DKNTK_QT',NULL,'PK_EXT_DKNTK_QT_ID','ID','IDX_EXT_DKNTK_QT_ID','ID','QLT-APP');
INSERT INTO tb_tables 
VALUES(2,'EXT_TKTMB_HDR',NULL,'PK_EXT_TKTMB_HDR_ID','ID','IDX_EXT_TKTMB_HDR_ID','ID','QLT-APP');
