INSERT INTO tb_package 
VALUES(421,'EXT_PCK_QLT_TKHAI','QLT-APP','user_objects@qlt',NULL);
INSERT INTO tb_package 
VALUES(501,'PNN_OWNER_EXT_PCK_PNN.sql','PNN-APP',NULL,'D:\Package');
INSERT INTO tb_package 
VALUES(502,'PNN_OWNER_EXT_PCK_PNN_BODY.sql','PNN-APP',NULL,'D:\Package');
INSERT INTO tb_package 
VALUES(341,'QLT_OWNER_EXT_PCK_QLT_TKHAI.sql','QLT-APP',NULL,'D:\Package');
INSERT INTO tb_package 
VALUES(342,'QLT_OWNER_EXT_PCK_QCT_TKHAI.sql','QCT-APP',NULL,'D:\Package');
INSERT INTO tb_package 
VALUES(121,'EXT_PCK_QCT_TKHAI','QCT-APP','user_objects@qlt',NULL);
INSERT INTO tb_package 
VALUES(422,'QLT_OWNER_EXT_PCK_QLT_TKHAI_BODY.sql','QLT-APP',NULL,'D:\Package');
INSERT INTO tb_package 
VALUES(423,'QLT_OWNER_EXT_PCK_QCT_TKHAI_BODY.sql','QCT-APP',NULL,'D:\Package');
