/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HelpAndSupport.java
 *
 * Created on May 2, 2012, 1:43:38 PM
 */
package com.pit.help.sources;

import java.net.URL;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.event.HyperlinkEvent;
import com.pit.system.Constants;
import java.util.LinkedList;

/**
 *
 * @author manhtv3
 */
public class HelpAndSupport extends javax.swing.JFrame {

    private LinkedList<HtmlPageNode> listHtmlPage;
    private HtmlPageNode currentPageNode;
    private HtmlPage currentPage;

    /** Creates new form HelpAndSupport */
    public HelpAndSupport() {
        initComponents();
        listHtmlPage = new LinkedList<HtmlPageNode>();
        epHelp.setEditable(false);
        try {
            currentPage = new HtmlPage();
            currentPage.setUrl(new URL(new File(Constants.FORDER_CONTAINS_HTML_PATH, "Index.html").toURI().toURL().toString()));
            currentPageNode = new HtmlPageNode(currentPage, null, null);
            listHtmlPage.add(currentPageNode);

            epHelp.setPage(currentPage.getUrl());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        epHelp = new javax.swing.JEditorPane();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.pit.convert.ConvertPSCDVATApp.class).getContext().getResourceMap(HelpAndSupport.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        epHelp.setName("epHelp"); // NOI18N
        epHelp.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                epHelpHyperlinkUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(epHelp);

        btnBack.setText(resourceMap.getString("btnBack.text")); // NOI18N
        btnBack.setEnabled(false);
        btnBack.setName("btnBack"); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setText(resourceMap.getString("btnNext.text")); // NOI18N
        btnNext.setEnabled(false);
        btnNext.setName("btnNext"); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addContainerGap(488, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnNext))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void epHelpHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_epHelpHyperlinkUpdate
        if (evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
            try {
                HtmlPage page = new HtmlPage(evt.getURL());
                HtmlPageNode pageNode = new HtmlPageNode(page, null, currentPageNode);
                currentPageNode.setNext(pageNode);                
                currentPageNode = pageNode;                
                currentPage = currentPageNode.getPage();

                epHelp.setPage(currentPage.getUrl());
                btnBack.setEnabled(true);
                btnNext.setEnabled(false);                
            } catch (IOException ioe) {
                ioe.printStackTrace();
            }
        }
    }//GEN-LAST:event_epHelpHyperlinkUpdate

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        HtmlPageNode node = currentPageNode.getPrevious();
        currentPageNode = node;
        currentPage = currentPageNode.getPage();
        try {
            epHelp.setPage(currentPage.getUrl());
            btnNext.setEnabled(true);
        } catch (IOException ex) {
            ex.printStackTrace();
        }

        if (currentPageNode.getPrevious() == null) {
            btnBack.setEnabled(false);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        HtmlPageNode node = currentPageNode.getNext();
        currentPageNode = node;
        currentPage = currentPageNode.getPage();
        try {
            epHelp.setPage(currentPage.getUrl());
            btnBack.setEnabled(true);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
        if (currentPageNode.getNext() == null)
        {
            btnNext.setEnabled(false);
        }
    }//GEN-LAST:event_btnNextActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JEditorPane epHelp;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
